version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: legendbookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  legendbookstore-service:
    image: postgres:latest
    ports:
      - 5432:5432
    depends_on:
      - db